### ISSUE TITLE
Scaffold blog application

### ISSUE THREAD

**Issue by lzaaldian** [lzaaldian/personal-blog#1]
# Tasks

- [x] Create users table migration
- [x] Scaffold admin features (using blog posts)
- [x] Scaffold manage categories
- [x] Scaffold manage tags

# Attributes

**Posts**

- title
- excerpt
- content
- hero_image
- slug
- tags
- category_id
- is_draft

**Categories**

- name

**Tags**

- name
