### ISSUE TITLE
Configure template and styles

### ISSUE THREAD

**Issue by lzaaldian** [lzaaldian/personal-blog#2]
# Tasks

- [x] Update Bootstrap to 3.3.7
- [x] Update jQuery
- [x] Implement Bootstrap dashboard template
- [x] Configure log in page
