### ISSUE TITLE
Manage blog posts

### ISSUE THREAD

**Issue by lzaaldian** [lzaaldian/personal-blog#3]
# Tasks

- [ ] Use DataTables to display list of posts
- [ ] Add new post
- [ ] View post details
- [ ] Edit a post
- [ ] Delete a post
