### ISSUE TITLE
Manage categories

### ISSUE THREAD

**Issue by lzaaldian** [lzaaldian/personal-blog#4]
# Tasks

- [ ] Use DataTables to display list of categories
- [ ] Add new category
- [ ] Edit a category
- [ ] Delete a category

## Additional

- [ ] When deleting a category, ask the user whether he want to:

- Delete all posts under deleted category
- or, change all posts from deleted category to uncategorized
